repos:
  - repo: local
    hooks:
      - id: bump2version
        name: bump2version
        entry: bump2version patch --allow-dirty
        language: system
        always_run: true
        pass_filenames: false
        exclude: .bumpversion.cfg
