repos:
  - repo: local
    hooks:
      - id: bump2version
        name: bump2version
        entry: bump2version minor
        language: system
        always_run: false
        pass_filenames: false
